; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dfrobot_firebeetle2_esp32e]
platform      = espressif32
board         = dfrobot_firebeetle2_esp32e
framework     = arduino
monitor_speed = 115200

lib_deps =
    DFRobot/DFRobot_GDL
    DFRobotDFPlayerMini
    adafruit/MAX6675 library

; ---- Optional build flags ----
; Uncomment to select audio routing (default DFPlayer only)
; build_flags = 
;   -DAUDIO_OUT_BT=1 
;   -DAUDIO_OUT_DFPLAYER=0

; (optional) lock your ports
; upload_port  = COM7
; monitor_port = COM7
; monitor_rts  = 0
; monitor_dtr  = 0
